volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: foodgram-db
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: foodgram-backend
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - media:/app/media/
      - static:/app/static/
    restart: always

  frontend:
    container_name: foodgram-front
    build: ./frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    container_name: foodgram-nginx
    image: nginx:1.25.4-alpine-slim
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
