# Generated by Django 3.2 on 2025-01-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20241225_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
