RECIPE_PER_PAGE = 6
EMAIL_LENGTH = 254
FIRST_LAST_NAME_LENGTH = 150
MAX_COOKING_TIME = 1000
MIN_COOKING_TIME = 1
RICIPE_NAME_MAX_LENGTH = 200
TAG_NAME_MAX_LENGTH = 100
TAG_SLUG_MAX_LENGTH = 100

INGREDIENTS_NAME_MAX_LENGTH = 200
INGREDIENTS_ME_MAX_LENGTH = 50

MIN_INGREDIENT_AMOUT = 1
MAX_INGREDIENT_AMOUT = 5000
